### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by sdwolfe32** [natdm/go-types-atom#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [go-types](https://github.com/natdm/go-types-atom) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/swolfe/.atom/packages/go-types/lib/go-types-view.js:56

TypeError: Cannot read property 'item' of undefined
    at /packages/go-types/lib/go-types-view.js:56:79
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -1:39.5.0 core:confirm (input.hidden-input)
     -1:12.3.0 core:select-all (input.hidden-input)
     -1:12.2.0 core:paste (input.hidden-input)
     -1:11.9.0 core:confirm (input.hidden-input)
     -0:55.1.0 core:save (input.hidden-input)
     -0:29.1.0 go-types:toggle (input.hidden-input)
  3x -0:27.1.0 core:save (input.hidden-input)
     -0:04.3.0 go-types:toggle (input.hidden-input)
     -0:01.9.0 core:save (atom-pane.pane)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
busy-signal 1.4.1 
cucumber 0.6.0 
file-icons 2.1.6 
git-blame 1.1.1 
git-plus 7.8.1 
go-debug 1.3.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
go-types 0.4.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-golinter 1.2.2 
linter-ruby 1.2.5 
linter-ui-default 1.5.4 
linter-xmllint 1.4.1 
xml-formatter 0.10.0 
```

**Comment by natdm** [comment]
Fixed.
